# Generated by Django 3.0.4 on 2020-04-19 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200419_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 12, 21, 31, 307857)),
        ),
    ]
